image: node:latest

cache:
  paths:
  - browser/node_modules/
  - /usr/local/lib/node_modules/

before_script:
- npm install --unsafe-perm -g now

browser_test:
  stage: test
  script:
  - cd browser
  - npm install
  - npm test

deploy_browser_preview:
  stage: deploy
  script:
  - cd browser
  - now --token $NOW_DEPLOY_TOKEN && now alias ${CI_ENVIRONMENT_SLUG}.browser.town --token $NOW_DEPLOY_TOKEN
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.browser.town
    on_stop: cleanup_browser_review

deploy_browser_alias:
  stage: deploy
  when: manual
  only:
  - master
  script:
  - cd browser
  - now --token $NOW_DEPLOY_TOKEN && now alias --token $NOW_DEPLOY_TOKEN
  environment:
    name: public
    url: https://browser.town

cleanup_browser_review:
  stage: deploy
  variables:
    GIT_STRATEGY: none
    ALIAS_URL: $CI_ENVIRONMENT_SLUG.browser.town
    DEPLOYMENT_URL: $(now --token $NOW_DEPLOY_TOKEN alias ls | awk "/${CI_ENVIRONMENT_SLUG}.browser.town/ {print \$1}")
  script:
  - now --token $NOW_DEPLOY_TOKEN alias rm $ALIAS_URL
  - now --token $NOW_DEPLOY_TOKEN rm --safe --yes $DEPLOYMENT_URL
  when: manual
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
